### ISSUE TITLE
Address information of the selected ServicePoint is missing from sales emails and the customer account pages

### ISSUE THREAD

**Issue by aadmathijssen** [dhlparcel/plugin-magento2-release#11]
When a customer has placed an order with the `dhlparcel_servicepoint` shipping method, the name of the selected ServicePoint is shown in the shipping method block in sales emails and the customer account pages. However, the address information of the ServicePoint is missing.

This means that the customer cannot obtain the address anymore using the website where he/she just placed an order (the only way is to go the checkout again and use the ServicePoint chooser again, but that feels odd).

**Comment by petraheuts** [comment]
Hi Aad, We improved this in our current release, thanks for contributing :)

**Comment by roerlemans** [comment]
Thanks again Aad, for finding and reporting the bugs you find.

**Comment by aadmathijssen** [comment]
Hi @ronn0,

Thanks for the reply.

However, I don't think this issue is resolved. Although the name of a selected ServicePoint is displayed in the sales emails and customer account pages, the address (street, city, country) of the ServicePoint is not.

Can you please reopen the ticket?

Thanks.

Aad
