### ISSUE TITLE
Preferred delivery times is missing

### ISSUE THREAD

**Issue by mikehenze** [dhlparcel/plugin-magento2-release#12]
The preferred delivery times block is no longer displayed after updating to Magento 2.3.4 / DHL 1.0.9
https://prnt.sc/r5mb1u

**Comment by petraheuts** [comment]
Hi Mike, We improved our time windows in the current release. Hopes this solves your issue. Otherwise let us know and we'll support you via cimparcel@dhl.com.

**Comment by roerlemans** [comment]
Thanks AGAIN(!) mike for your feedback and help. This issue should be resolved in our last release. 

Many thanks for your help and contribution.
