### ISSUE TITLE
Undefined property

### ISSUE THREAD

**Issue by atty31** [dhlparcel/plugin-magento2-release#15]
Hi,

**Issue description:**

- Enable **Debug mode** from **Developer Settings** 

- Go to the order view page from backend and press the **DHL label request** button

- the controller will return you this result "[null]"

Other info: checking out the controller, I see that this object from it:
`$this->notificationService` is not defined anywhere - "Property 'notificationService' not found in Labelrequest"

 See: https://github.com/dhlparcel/plugin-magento2-release/blob/master/Controller/Adminhtml/Shipment/Labelrequest.php#L73

**Comment by roerlemans** [comment]
Thanks for your contribution and your feedback. We will fix this in our next release.
