### ISSUE TITLE
wrong css reference in layout file onestepcheckout_index_index.xml

### ISSUE THREAD

**Issue by GuidoHub** [dhlparcel/plugin-magento2-release#16]
In file view/frontend/layout/onestepcheckout_index_index.xml you still use 

`<css src="DHLParcel_Shipping::css/deliverytimes.css" />`

But from 1.0.11 it has changed to 

`<css src="DHLParcel_Shipping::css/deliveryoptions.css" />`

In file view/frontend/layout/checkout_index_index.xml it's used correctly.

You should also check the JS on row 36, you also using an old file there.

`<item name="component" xsi:type="string">DHLParcel_Shipping/js/view/deliverytimes-info</item>`

**Comment by roerlemans** [comment]
I'd like to thank you for your help! We will fix this in our next release. Thanks for your contribution.
