### ISSUE TITLE
Call to a member function getUrl() on null

### ISSUE THREAD

**Issue by FedeltaMedia** [dhlparcel/plugin-magento2-release#17]
After updating Magento to 2.3.4, applying patch 2.3.5-p1 and updating the DHLparcel plugin to 1.0.13. The Bulk **Actions > DHL Parcel > Create labels** doesn't work anymore.

The error I'm getting is:
```
<br /><table class="shipment-track"><thead><tr><th>Verzonden door</th><th>Tracking-nummer</th></tr></thead><tbody> <tr><td>DHL Parcel:</td><td><a href="<br />
<b>Fatal error</b>:  Uncaught Error: Call to a member function getUrl() on null in /var/domains/xxx.com/application/var/view_preprocessed/pub/static/app/design/frontend/Mgs/claue/Magento_Sales/templates/email/shipment/track.phtml:1
Stack trace:
#0 /var/domains/xxx.com/application/vendor/magento/framework/View/TemplateEngine/Php.php(59): include()
#1 /var/domains/xxx.com/application/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\TemplateEngine\Php-&gt;render(Object(Magento\Framework\View\Element\Template\Interceptor), '/var/domains/an...', Array)
#2 /var/domains/xxx.com/application/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\View\TemplateEngine\Php\Interceptor-&gt;___callParent('render', Array)
#3 /var/domains/xxx.com/application/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\TemplateEngine\Php\Interceptor-&gt;Magento\Framework\Intercepti in <b>/var/domains/xxx.com/application/var/view_preprocessed/pub/static/app/design/frontend/Mgs/claue/Magento_Sales/templates/email/shipment/track.phtml</b> on line <b>1</b><br />
```
In the Magento_Sales/templates/email/shipment/track.phtml file, (which we copied from the original Magento file) the tracking code is called using:

```
<a href="<?= $block->escapeUrl($block->getTrackingUrl()->getUrl($_item)) ?>" target="_blank">
  <?= $block->escapeHtml($_item->getNumber()) ?>
</a>
```

For some weird reason, when we clear cache and recompile it works for the first order. But then on the second order, it stops working again. What is causing this and how to fix this issue?

**Comment by roerlemans** [comment]
What does happen when you delete your theme overwrite in `app/design/frontend/Mgs/claue/Magento_Sales/templates/email/shipment/track.phtml`?

**Comment by FedeltaMedia** [comment]
Same issue. We made an override to try and fix the problem

**Comment by rolfdenhartog** [comment]
Hi @Fidelity88,

Were you able to fix the problem?

**Comment by FedeltaMedia** [comment]
@rolfdenhartog No the problem still exists. The DHL 'create label' function is one of the most important features we use. So we actually postponed the Magento update specifically because of this problem.

Are you having the same issues?

**Comment by rolfdenhartog** [comment]
I've tried to reproduce the bug, but I couldn't. I'll discuss it with the other team members.

**Comment by rolfdenhartog** [comment]
Hi @Fidelity88, another colleague tried te reproduce the issue, but couldn't too. Would you please send an e-mail to parcel@dhl.com to discuss on-site support? Thanks!
