### ISSUE TITLE
Validation on hidden field when `Create DHL shipping label` not selected

### ISSUE THREAD

**Issue by joeriLock93** [dhlparcel/plugin-magento2-release#21]
Ran into a bug where it looked like the `Submit shipment` button was not working.
But in reality there is an hidden field validated even when this option is no selected.

**Step to recreate**:
1. Install dhlparcel/magento2-plugin:1.0.*
2. Create order with an order id thats 15 characters or longer
3. Go to order in backend
4. Go to Ship
5. Make sure `Create DHL shipping label` checkbox is disabled
6. Press `Submit shipment`

**Expected**:
Shipment is created

**Actual**:
Nothing

**Work around:**
1. Check `Create DHL shipping label`
2. Remove content form `reference`
3. Uncheck `Create DHL shipping label`
4. Create shipment as usual.

Other info
dhlparcel/magento2-plugin: 1.0.13
Magento: 2.3.5-p1

**Comment by roerlemans** [comment]
Hi @joeriLock93, thanks for your bug report. I'd like to let you know I'm fixing this issue as we speak. Sorry for the inconvenience. 

It will be fixed in our next release.

**Comment by roerlemans** [comment]
This bug is fixed in v1.0.16:
https://github.com/dhlparcel/plugin-magento2-release/releases/tag/v1.0.16

Thanks again.
