### ISSUE TITLE
Multiple shipping tacking numbers & labels are being created

### ISSUE THREAD

**Issue by gunjanbgpl** [dhlparcel/plugin-magento2-release#23]
We are running DHL parcel shipping ver 1.0.14 with Magento Ver 2.3.5(with bol.com module integrated)
& everything works well for now, exept one thing
When we create DHL parcel label, it creates multiple tracking numbers in a shippment.
Let us know if you have any update on this.

**Comment by petraheuts** [comment]
Hi we can have a look at this, please send you contact details to parcel@dhl.com and refer to your message in GitHub so we can have a support colleague contact you about this.
