### ISSUE TITLE
Error when creating labels

### ISSUE THREAD

**Issue by Aquive** [dhlparcel/plugin-magento2-release#24]
When creating labels sometimes an occurs. See screenshot below. How can I find the root cause?

- DHL Parcel version: 1.0.10
- Magento version: 2.3.2

![DHL-error-png-1905×891-](https://user-images.githubusercontent.com/197229/93988162-b149ba00-fd88-11ea-93b4-2663b1895e80.png)

**Comment by petraheuts** [comment]
please try to update to the newest version and if the issue persists please add a way to reproduce your issue.
