### ISSUE TITLE
Do not add trackings for return labels (or improve its presentation)

### ISSUE THREAD

**Issue by aadmathijssen** [dhlparcel/plugin-magento2-release#27]
When creating a shipment using the "Create DHL shipping label" option and the "Return label" service, a shipment is created with two trackings named "DHL Parcel" and "DHL Parcel Return Label".

This seems to be the only way to distinguish these trackings for users and admins. 
More precisely, in the following places a page is opened that does not indicate whether the tracking number concerns a shipping label or a return label:
* Shipment emails, after clicking on a link in the "Tracking Number" column.
* Frontend, on the my account pages, the order shipments tab of an order: after clicking on any of the links following the "Tracking Number(s)" heading, or after clicking on the "Track this shipment" link.
* Admin, on the sales order view page after clicking on the "Track Order" link.
* Admin, on the sales shipment view page after clicking on the links in the "Number" column, of after clicking on the "Track this shipment" link.

Also, return labels contain a link to the https://www.dhlparcel.nl/nl/volg-uw-zending page, just like standard shipping labels, so from the link itself the type cannot be derived.

In order to resolve this, the presentation of the DHL Parcel Return Label tracking should be improved.

However, I think the following solution is better:

_Do not add tracking for return labels at all._

Rationale:

1. The return label is created at the same time the shipping label is created; at this time the customer hasn't returned anything, as he/she didn't receive any package yet. So it is not necessary to show the labels in the shipment email.
2. Because in most cases, a customer doesn't return anything, it is confusing to show a tracking number. So it seems better to remove this from the my account pages as well.
3. In the admin, the actual DHL Labels can be found in the sales order and sales shipment grids. Adding a tracking link there doesn't add anything useful.

**Comment by roerlemans** [comment]
We have this feature request on our backlog, thanks to you. Thanks (again).
