### ISSUE TITLE
Maximum/Minimum Order Amount

### ISSUE THREAD

**Issue by bst2002git** [dhlparcel/plugin-magento2-release#28]
Hello,

Maximum/Minimum Order Amount is missing, needed to show or hide Shipping Method.

Or something like this under the menu  "General Shipping Settings/Shipping Methods for DHL Shipping" in Module ""dhl/module-shipping-m2":
https://github.com/netresearch/dhl-module-shipping-m2.git

**Comment by roerlemans** [comment]
I will discuss this feature request with our product owner. Thanks for leaving your feedback.

**Comment by roerlemans** [comment]
For now you can react this with the price matrix option
