### ISSUE TITLE
Pickup point not set correctly

### ISSUE THREAD

**Issue by timbaltissen** [dhlparcel/plugin-magento2-release#29]
When going through checkout and selecting to use a pickup point it auto selects the most nearby point, most of the customer will like this and want to use this point. However when clicking to go to the next step it shows a message that says a pickup point should be chosen. See attached screenshots. What I did was just select the pickup method en than click on "next step". You can see Computerkruis is selected, but in the second screenshot you see it says to select a pickup point. 

![Screen Shot 2021-02-03 at 09 17 39](https://user-images.githubusercontent.com/5435433/106718246-14820d80-6601-11eb-9c63-991dfa898377.png)
![Screen Shot 2021-02-03 at 09 17 47](https://user-images.githubusercontent.com/5435433/106718255-164bd100-6601-11eb-883d-d47263e844c2.png)

**Comment by roerlemans** [comment]
Sorry for the late answer on this issue. We have fixed this issue in an earlier release, but didn't came back to you. Sorry for that. Do you still have this problem?

**Comment by timbaltissen** [comment]
All fine now, thanks!
