### ISSUE TITLE
ServicePoint ID is stored for shipment if ServicePoint is not the selected shipping method

### ISSUE THREAD

**Issue by kanduvisla** [dhlparcel/plugin-magento2-release#3]
Tested on M2.2.9 / v1.0.6:

If I select "Home Delivery" as shipping method, somehow a ServicePoint ID still gets stored for my order:

<img width="568" alt="Screen Shot 2019-09-17 at 2 48 48 PM" src="https://user-images.githubusercontent.com/346681/65043002-636eca80-d95a-11e9-8bfb-e7b6cd91b914.png">

<img width="288" alt="Screen Shot 2019-09-17 at 2 50 20 PM" src="https://user-images.githubusercontent.com/346681/65043074-8305f300-d95a-11e9-9f00-86e2cea454e3.png">

This is somewhat confusing. You would expect this field to be empty if the selected shipping method is "Home Delivery"

**Comment by Dunduro** [comment]
I believe this issue to have been fixed in version 1.0.7, instead of checking if the value exists the code now also checks if the required method is selected.
https://github.com/dhlparcel/plugin-magento2-release/blob/821d7a55f34d4cdabf9e34fdcd89b74c4fd5dadf/Observer/Checkout/ServicePoint.php
