### ISSUE TITLE
You have included the Google Maps JavaScript API multiple times on this page. This may cause unexpected errors.

### ISSUE THREAD

**Issue by bst2002git** [dhlparcel/plugin-magento2-release#32]
After installing this Module i get this Error/Warning in the JavascriptConsole:
"You have included the Google Maps JavaScript API multiple times on this page. This may cause unexpected errors."

I'v also installed a checkout module (since month) with address-completation using google Maps.

**Comment by bst2002git** [comment]
I also noticed  that it block the complete html form fields from filling out -> so no checkout can be done.
I think the problem could be in this file servicepoint-loader.js

**Comment by Krachtstroom** [comment]
Same problem here. The overlay for Google maps is completely covering my checkout. It's useless this way.

**Comment by roerlemans** [comment]
Sorry for the late answer. The blocking form should be fixed. 

It's hard to fix the other issue, because we depend on a specific version of the Google Maps API. I will discuss this with the author's of our Service Point locator component.
