### ISSUE TITLE
Class 'DHLParcel\Shipping\Block\Adminhtml\Authentication\Test\Interceptor' not found

### ISSUE THREAD

**Issue by piuga** [dhlparcel/plugin-magento2-release#34]
Hello,

For production mode with composer optimization Level 2, and Test folder excluded from autoload, like on core composer.json https://github.com/magento/magento2/blob/2.4-develop/composer.json#L371, will generate this error:
"main.CRITICAL: Error: Class 'DHLParcel\Shipping\Block\Adminhtml\Authentication\Test\Interceptor' not found" and "Shipping Methods" configuration tab is not accessible.
Can you please rename the DHLParcel\Shipping\Block\Adminhtml\Authentication\Test and DHLParcel\Shipping\Controller\Adminhtml\Authentication\Test to something else, like TestConnection or TestAuthentication?
Thank you!

**Comment by roerlemans** [comment]
Sorry for our late answer, I wille place this request on our backlog. I think we can fix this in the next release.
