### ISSUE TITLE
Module creates multiple shipping labels for order

### ISSUE THREAD

**Issue by IvoJongmans** [dhlparcel/plugin-magento2-release#35]
Hi,

In the magento backend multiple DHL labels are being attached to an order. I've attached an image of an order where this occurs. 

PHP 7.2
Magento 2.3.3

![DHL](https://user-images.githubusercontent.com/48712793/132644375-88c06c03-b696-404f-8236-0433f332c833.png)

**Comment by roerlemans** [comment]
Thanks for submitting an issue. Sorry for our late response. Do you still have this problem?
