### ISSUE TITLE
After creating labels with mass action, order grid jumps to first order date

### ISSUE THREAD

**Issue by Steekvlam** [dhlparcel/plugin-magento2-release#36]
We've got a bug with creating the labels.
After selecting a couple of orders in the sales order grid and creating the DHL labels, after creating the grid somehow sorts the grid to the very first order date.

Already checked the ui_bookmark table, nothing changed there..
To go back to the latest order we need to click the purchase date twice, which takes a couple of minutes each click, its pretty annoying..

Before create labels grid view:
![step-1](https://user-images.githubusercontent.com/3660692/138873642-5cdc6c52-a37d-496d-9270-f19e16657896.jpg)

After creating labels grid view:
![step-2](https://user-images.githubusercontent.com/3660692/138873656-545c871e-19b2-4dd6-9dce-e62d250195bd.jpg)

DHL version: v1.0.27
Magento version: 2.4.2-p2

**Comment by roerlemans** [comment]
Sorry for our late response. We did some improvements on this part. Do you still have this issue?
