### ISSUE TITLE
Feature Request: Adding servicepoint address to order extension attributes

### ISSUE THREAD

**Issue by ridder-js** [dhlparcel/plugin-magento2-release#37]
For a project i am working on i kneed to know the address of a chosen servicepoint in the rest api, because this address needs to be communicated to a third party system.

It would be very convenient if i am able to extract this servicepoint address from the extension attributes. 

I can imagine this data not being provided in the extension attributes is by design because the data needs to be retrieved from dhl. An api endpoint to get the address by the id currently provided in the extension attributes would also work.

Thanks for considering my request.

**Comment by roerlemans** [comment]
Sorry for our late response. You're right we have an API for that. Do you still need it? We can help you with those endpoints if needed.

**Comment by ridder-js** [comment]
Thanks for replying, we currently dont need the api since the customer has found an alternative method of transfering the orders containing a service point (i suspect he copies or alters them manually). If i have a need for the api docs in the future i will let you know!
