### ISSUE TITLE
Translation 'Choose a different DHL ServicePoint

### ISSUE THREAD

**Issue by Paulsky** [dhlparcel/plugin-magento2-release#38]
Hello,

I would like to translate this string, but I do not think this is possible with i18n. Please see line:

https://github.com/dhlparcel/plugin-magento2-release/blob/95a5379df7c9cfb75239550dc8abae2045621ed7/view/frontend/web/template/servicepoint-info.html#L8

**Comment by roerlemans** [comment]
Sorry for our late response. We did fix this in an earlier release.
