### ISSUE TITLE
Sales order grid bulk action: Class argument is invalid: DHLParcel\Shipping\Ui\Bulk\Actions

### ISSUE THREAD

**Issue by Nielex** [dhlparcel/plugin-magento2-release#4]
Hi guys,

We experience an issue with your module version 1.0.7 and below.

Just after upgrading from Magento 2.3.2 to 2.3.2-p2 and opening the Sales Order or Sales Shipment grid this error occurs:

<pre>1 exception(s):

Exception #0 (InvalidArgumentException): Class argument is invalid: DHLParcel\Shipping\Ui\Bulk\Actions
#1 Magento\Framework\Data\Argument\InterpreterInterface\Proxy->evaluate() called at [vendor/magento/framework/Data/Argument/Interpreter/Composite.php:61]
#2 Magento\Framework\Data\Argument\Interpreter\Composite->evaluate() called at [vendor/magento/module-ui/Config/Data.php:164]
#3 Magento\Ui\Config\Data->evaluateComponentArguments() called at [vendor/magento/module-ui/Config/Data.php:167]
#4 Magento\Ui\Config\Data->evaluateComponentArguments() called at [vendor/magento/module-ui/Config/Data.php:167]
#5 Magento\Ui\Config\Data->evaluateComponentArguments() called at [vendor/magento/module-ui/Config/Data.php:167]
#6 Magento\Ui\Config\Data->evaluateComponentArguments() called at [vendor/magento/module-ui/Config/Data.php:111]
#7 Magento\Ui\Config\Data->initData() called at [vendor/magento/module-ui/Config/Data.php:136]
#8 Magento\Ui\Config\Data->get() called at [vendor/magento/framework/View/Layout/Reader/UiComponent.php:100]
#9 Magento\Framework\View\Layout\Reader\UiComponent->interpret() called at [vendor/magento/framework/View/Layout/ReaderPool.php:105]
#10 Magento\Framework\View\Layout\ReaderPool->interpret() called at [vendor/magento/framework/View/Layout/Reader/Container.php:89]
#11 Magento\Framework\View\Layout\Reader\Container->interpret() called at [vendor/magento/framework/View/Layout/ReaderPool.php:105]
#12 Magento\Framework\View\Layout\ReaderPool->interpret() called at [vendor/magento/framework/View/Page/Config/Reader/Body.php:68]
#13 Magento\Framework\View\Page\Config\Reader\Body->interpret() called at [vendor/magento/framework/View/Layout/ReaderPool.php:105]
#14 Magento\Framework\View\Layout\ReaderPool->interpret() called at [vendor/magento/framework/View/Layout.php:325]
#15 Magento\Framework\View\Layout->generateElements() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:89]
#16 Magento\Framework\View\Layout\Interceptor->generateElements() called at [vendor/magento/framework/View/Layout/Builder.php:129]
#17 Magento\Framework\View\Layout\Builder->generateLayoutBlocks() called at [vendor/magento/framework/View/Page/Builder.php:55]
#18 Magento\Framework\View\Page\Builder->generateLayoutBlocks() called at [vendor/magento/framework/View/Layout/Builder.php:65]
#19 Magento\Framework\View\Layout\Builder->build() called at [vendor/magento/framework/View/Layout.php:253]
#20 Magento\Framework\View\Layout->build() called at [vendor/magento/framework/View/Layout.php:875]
#21 Magento\Framework\View\Layout->getBlock() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:414]
#22 Magento\Framework\View\Layout\Interceptor->getBlock() called at [vendor/magento/module-backend/Model/View/Result/Page.php:26]
#23 Magento\Backend\Model\View\Result\Page->setActiveMenu() called at [generated/code/Magento/Backend/Model/View/Result/Page/Interceptor.php:24]
#24 Magento\Backend\Model\View\Result\Page\Interceptor->setActiveMenu() called at [vendor/magento/module-sales/Controller/Adminhtml/Order.php:140]
#25 Magento\Sales\Controller\Adminhtml\Order->_initAction() called at [vendor/magento/module-sales/Controller/Adminhtml/Order/Index.php:19]
#26 Magento\Sales\Controller\Adminhtml\Order\Index->execute() called at [generated/code/Magento/Sales/Controller/Adminhtml/Order/Index/Interceptor.php:24]
#27 Magento\Sales\Controller\Adminhtml\Order\Index\Interceptor->execute() called at [vendor/magento/framework/App/Action/Action.php:108]
#28 Magento\Framework\App\Action\Action->dispatch() called at [vendor/magento/module-backend/App/AbstractAction.php:231]
#29 Magento\Backend\App\AbstractAction->dispatch() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#30 Magento\Sales\Controller\Adminhtml\Order\Index\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#31 Magento\Sales\Controller\Adminhtml\Order\Index\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/module-backend/App/Action/Plugin/Authentication.php:143]
#32 Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch() called at [vendor/magento/framework/Interception/Interceptor.php:135]
#33 Magento\Sales\Controller\Adminhtml\Order\Index\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#34 Magento\Sales\Controller\Adminhtml\Order\Index\Interceptor->___callPlugins() called at [generated/code/Magento/Sales/Controller/Adminhtml/Order/Index/Interceptor.php:39]
#35 Magento\Sales\Controller\Adminhtml\Order\Index\Interceptor->dispatch() called at [vendor/magento/framework/App/FrontController.php:159]
#36 Magento\Framework\App\FrontController->processRequest() called at [vendor/magento/framework/App/FrontController.php:99]
#37 Magento\Framework\App\FrontController->dispatch() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#38 Magento\Framework\App\FrontController\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#39 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#40 Magento\Framework\App\FrontController\Interceptor->___callPlugins() called at [generated/code/Magento/Framework/App/FrontController/Interceptor.php:26]
#41 Magento\Framework\App\FrontController\Interceptor->dispatch() called at [vendor/magento/framework/App/Http.php:137]
#42 Magento\Framework\App\Http->launch() called at [generated/code/Magento/Framework/App/Http/Interceptor.php:24]
#43 Magento\Framework\App\Http\Interceptor->launch() called at [vendor/magento/framework/App/Bootstrap.php:261]
#44 Magento\Framework\App\Bootstrap->run() called at [pub/index.php:40]'

I think this has something todo with the update in Magento 2.3.3 and how Ui components and mass actions are defined.

**Comment by Nielex** [comment]
On my development env. the following changes in this pull-request fixed it:

https://github.com/dhlparcel/plugin-magento2-release/pull/5

**Comment by GuidoHub** [comment]
Also occurs on Magento 2.2.10

**Comment by kanduvisla** [comment]
I can also confirm this issue in Magento 2.2.10

**Comment by roerlemans** [comment]
We just released V1.0.8, this should fix this issue. Thanks for your patience 
https://github.com/dhlparcel/plugin-magento2-release/releases/tag/v1.0.8
