### ISSUE TITLE
2.4.4 compatibility

### ISSUE THREAD

**Issue by jellesiderius** [dhlparcel/plugin-magento2-release#40]
Hi,

One of our clients is trying to update to Magento 2.4.4. Now we're not able to update with this module in it because of the required package "guzzlehttp/guzzle" requirement of 6.0+. magento/framework requires ^7.3.0. Could this please be looked into?

**Comment by paul-stolk-webdiensten** [comment]
Hi, are there any plans or a schedule for when 2.4.4 is supported? 2.4.4 is out now for 1.5 months

**Comment by roerlemans** [comment]
Sorry for our late response. We did add support for 2.4.4. Our apologies for the inconvenience
