### ISSUE TITLE
Removing / updating the module db problems 

### ISSUE THREAD

**Issue by jdereus87** [dhlparcel/plugin-magento2-release#42]
Problem: Database cleanup & update leave a few problems
Update M2.3.2 > M2.4.4 and DHL module from 1.10 -> 1.37

**Removing the DHL module:**
In doing an update from magento I had removed the DHL module only to install it later again. Removing the module creates errors in the backend when opening a product:
Class "DHLParcel\Shipping\Model\Entity\Attribute\Source\NoYes" does not exist.
The uninstall script does not seem to clean this up since it only removes the two created tables.

**Updating the DHL module:**
After installing the newest version the NoYes problem was solved logically. However in updating from 1.10 to 1.37 I got an identical error: Class "DHLParcel\Shipping\Model\Entity\Attribute\Source\BlackList" does not exist

It seems this was class was renamed. I noticed there is an entry in UpgradeData to rename this class, but it did not apply for some reason. I renamed it manually.

In general I wish there was a more solid cleanup and it might be a good moment to also start using the declerative schema.

Cheers

**Comment by roerlemans** [comment]
Sorry for the late response. We did fix this in an earlier release. Our apologies for the inconvenience
