### ISSUE TITLE
Error when shipping an order in the Admin 

### ISSUE THREAD

**Issue by jurgenmahn** [dhlparcel/plugin-magento2-release#45]
When creating a shipment in the admin, the page returns an 500 error.

`main.CRITICAL: Error: Call to a member function hasErrors() on null in /var/www/html/www/vendor/magento/module-shipping/Model/Carrier/AbstractCarrierOnline.php:489
Stack trace:
#0 /var/www/html/www/vendor/magento/module-shipping/Model/Shipping/Labels.php(163): Magento\Shipping\Model\Carrier\AbstractCarrierOnline->requestToShipment(Object(Magento\Shipping\Model\Shipment\Request))
#1 /var/www/html/www/vendor/magento/module-shipping/Model/Shipping/LabelGenerator.php(77): Magento\Shipping\Model\Shipping\Labels->requestToShipment(Object(Magento\Sales\Model\Order\Shipment\Interceptor))
#2 /var/www/html/www/vendor/magento/module-shipping/Controller/Adminhtml/Order/Shipment/Save.php(164): Magento\Shipping\Model\Shipping\LabelGenerator->create(Object(Magento\Sales\Model\Order\Shipment\Interceptor), Object(Magento\Framework\App\Request\Http))
#3 /var/www/html/www/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Shipping\Controller\Adminhtml\Order\Shipment\Save->execute()
#4 /var/www/html/www/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Shipping\Controller\Adminhtml\Order\Shipment\Save\Interceptor->___callParent('execute', Array)
#5 /var/www/html/www/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Shipping\Controller\Adminhtml\Order\Shipment\Save\Interceptor->Magento\Framework\Interception\{closure}()
#6 /var/www/html/www/generated/code/Magento/Shipping/Controller/Adminhtml/Order/Shipment/Save/Interceptor.php(23): Magento\Shipping\Controller\Adminhtml\Order\Shipment\Save\Interceptor->___callPlugins('execute', Array, Array)
#7 /var/www/html/www/vendor/magento/framework/App/Action/Action.php(111): Magento\Shipping\Controller\Adminhtml\Order\Shipment\Save\Interceptor->execute()
#8 /var/www/html/www/vendor/magento/module-backend/App/AbstractAction.php(151): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#9 /var/www/html/www/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Backend\App\AbstractAction->dispatch(Object(Magento\Framework\App\Request\Http))
#10 /var/www/html/www/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Shipping\Controller\Adminhtml\Order\Shipment\Save\Interceptor->___callParent('dispatch', Array)
#11 /var/www/html/www/vendor/magento/module-backend/App/Action/Plugin/Authentication.php(143): Magento\Shipping\Controller\Adminhtml\Order\Shipment\Save\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#12 /var/www/html/www/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch(Object(Magento\Shipping\Controller\Adminhtml\Order\Shipment\Save\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#13 /var/www/html/www/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Shipping\Controller\Adminhtml\Order\Shipment\Save\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#14 /var/www/html/www/generated/code/Magento/Shipping/Controller/Adminhtml/Order/Shipment/Save/Interceptor.php(32): Magento\Shipping\Controller\Adminhtml\Order\Shipment\Save\Interceptor->___callPlugins('dispatch', Array, Array)
#15 /var/www/html/www/vendor/magento/framework/App/FrontController.php(245): Magento\Shipping\Controller\Adminhtml\Order\Shipment\Save\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#16 /var/www/html/www/vendor/magento/framework/App/FrontController.php(212): Magento\Framework\App\FrontController->getActionResponse(Object(Magento\Shipping\Controller\Adminhtml\Order\Shipment\Save\Interceptor), Object(Magento\Framework\App\Request\Http))
#17 /var/www/html/www/vendor/magento/framework/App/FrontController.php(147): Magento\Framework\App\FrontController->processRequest(Object(Magento\Framework\App\Request\Http), Object(Magento\Shipping\Controller\Adminhtml\Order\Shipment\Save\Interceptor))
#18 /var/www/html/www/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#19 /var/www/html/www/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#20 /var/www/html/www/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#21 /var/www/html/www/generated/code/Magento/Framework/App/FrontController/Interceptor.php(23): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#22 /var/www/html/www/vendor/magento/framework/App/Http.php(116): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#23 /var/www/html/www/vendor/magento/framework/App/Bootstrap.php(264): Magento\Framework\App\Http->launch()
#24 /var/www/html/www/pub/index.php(33): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))
#25 {main} [] []`

Which makes sense if i check the function in 

vendor/dhlparcel/magento2-plugin/Model/Carrier.php

`    protected function _doShipmentRequest(\Magento\Framework\DataObject $request)
    {
        unset($request);
        return null;
    }`

![image](https://user-images.githubusercontent.com/47450782/192746134-c9d3adba-5e40-484c-afd2-71745ce542f3.png)

Just returning the original "\Magento\Framework\DataObject $request" seems to solve the issue

Tested with Magento 2.4.3-p1

**Comment by roerlemans** [comment]
Thank you for submitting an issue. Do you still have this issue? Sorry we did answer this late.
