### ISSUE TITLE
Exception: Deprecated Functionality: explode()

### ISSUE THREAD

**Issue by Paulsky** [dhlparcel/plugin-magento2-release#48]
We are receiving an error when filtering orders in de backend:  

`main.CRITICAL: Exception: Deprecated Functionality: explode(): Passing null to parameter #2 ($string) of type string is deprecated in /vendor/dhlparcel/magento2-plugin/Ui/Column/Labels.php on line 95 in /vendor/magento/framework/App/ErrorHandler.php:62`

We are on Magento 2.4.5, PHP 8.1

**Comment by roerlemans** [comment]
Thanks for leaving this issue. We did fix this in an earlier release. Our apologies for the inconvenience

**Comment by Paulsky** [comment]
Hello,

We still encounter this issue on 1.0.40. In which commit did you fix this issue?
