### ISSUE TITLE
Fresh install magento2 on php 8.1

### ISSUE THREAD

**Issue by mardedude1** [dhlparcel/plugin-magento2-release#50]
Error when opening on shipping methodes:

1 exception(s):
Exception #0 (Exception): Deprecated Functionality: trim(): Passing null to parameter #1 ($string) of type string is deprecated in /home/ictshop/public_html/vendor/dhlparcel/magento2-plugin/Model/Api/Connector.php on line 176

Exception #0 (Exception): Deprecated Functionality: trim(): Passing null to parameter #1 ($string) of type string is deprecated in /home/ictshop/public_html/vendor/dhlparcel/magento2-plugin/Model/Api/Connector.php on line 176
<pre>#1 trim() called at [vendor/dhlparcel/magento2-plugin/Model/Api/Connector.php:176]
#2 DHLParcel\Shipping\Model\Api\Connector->authenticate() called at [vendor/dhlparcel/magento2-plugin/Model/Api/Connector.php:103]
#3 DHLParcel\Shipping\Model\Api\Connector->request() called at [vendor/dhlparcel/magento2-plugin/Model/Api/Connector.php:70]
#4 DHLParcel\Shipping\Model\Api\Connector->get() called at [vendor/dhlparcel/magento2-plugin/Model/Service/Printing.php:49]
#5 DHLParcel\Shipping\Model\Service\Printing->getPrinters() called at [vendor/dhlparcel/magento2-plugin/Model/Config/Source/Printer.php:23]
#6 DHLParcel\Shipping\Model\Config\Source\Printer->toOptionArray() called at [vendor/magento/module-config/Model/Config/Structure/Element/Field.php:461]
#7 Magento\Config\Model\Config\Structure\Element\Field->_getOptionsFromSourceModel() called at [vendor/magento/module-config/Model/Config/Structure/Element/Field.php:379]
#8 Magento\Config\Model\Config\Structure\Element\Field->getOptions() called at [vendor/magento/module-config/Block/System/Config/Form.php:394]
#9 Magento\Config\Block\System\Config\Form->_initElement() called at [vendor/magento/module-config/Block/System/Config/Form.php:316]
#10 Magento\Config\Block\System\Config\Form->initFields() called at [vendor/magento/module-config/Block/System/Config/Form.php:256]
#11 Magento\Config\Block\System\Config\Form->_initGroup() called at [vendor/magento/module-config/Block/System/Config/Form.php:302]
#12 Magento\Config\Block\System\Config\Form->initFields() called at [vendor/magento/module-config/Block/System/Config/Form.php:256]
#13 Magento\Config\Block\System\Config\Form->_initGroup() called at [vendor/magento/module-config/Block/System/Config/Form.php:302]
#14 Magento\Config\Block\System\Config\Form->initFields() called at [vendor/magento/module-config/Block/System/Config/Form.php:256]
#15 Magento\Config\Block\System\Config\Form->_initGroup() called at [vendor/magento/module-config/Block/System/Config/Form.php:202]
#16 Magento\Config\Block\System\Config\Form->initForm() called at [vendor/magento/module-config/Block/System/Config/Form.php:542]
#17 Magento\Config\Block\System\Config\Form->_beforeToHtml() called at [vendor/magento/framework/View/Element/AbstractBlock.php:1094]
#18 Magento\Framework\View\Element\AbstractBlock->Magento\Framework\View\Element\{closure}() called at [vendor/magento/framework/View/Element/AbstractBlock.php:1099]
#19 Magento\Framework\View\Element\AbstractBlock->_loadCache() called at [vendor/magento/framework/View/Element/AbstractBlock.php:660]
#20 Magento\Framework\View\Element\AbstractBlock->toHtml() called at [vendor/magento/framework/View/Layout.php:578]
#21 Magento\Framework\View\Layout->_renderBlock() called at [vendor/magento/framework/View/Layout.php:555]
#22 Magento\Framework\View\Layout->renderNonCachedElement() called at [vendor/magento/framework/View/Layout.php:510]
#23 Magento\Framework\View\Layout->renderElement() called at [vendor/magento/framework/View/Element/AbstractBlock.php:507]
#24 Magento\Framework\View\Element\AbstractBlock->getChildHtml() called at [vendor/magento/module-config/view/adminhtml/templates/system/config/edit.phtml:32]
#25 include() called at [vendor/magento/framework/View/TemplateEngine/Php.php:71]
#26 Magento\Framework\View\TemplateEngine\Php->render() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#27 Magento\Framework\View\TemplateEngine\Php\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#28 Magento\Framework\View\TemplateEngine\Php\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#29 Magento\Framework\View\TemplateEngine\Php\Interceptor->___callPlugins() called at [generated/code/Magento/Framework/View/TemplateEngine/Php/Interceptor.php:23]
#30 Magento\Framework\View\TemplateEngine\Php\Interceptor->render() called at [vendor/magento/framework/View/Element/Template.php:263]
#31 Magento\Framework\View\Element\Template->fetchView() called at [vendor/magento/framework/View/Element/Template.php:293]
#32 Magento\Framework\View\Element\Template->_toHtml() called at [vendor/magento/module-backend/Block/Template.php:141]
#33 Magento\Backend\Block\Template->_toHtml() called at [vendor/magento/framework/View/Element/AbstractBlock.php:1095]
#34 Magento\Framework\View\Element\AbstractBlock->Magento\Framework\View\Element\{closure}() called at [vendor/magento/framework/View/Element/AbstractBlock.php:1099]
#35 Magento\Framework\View\Element\AbstractBlock->_loadCache() called at [vendor/magento/framework/View/Element/AbstractBlock.php:660]
#36 Magento\Framework\View\Element\AbstractBlock->toHtml() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#37 Magento\Config\Block\System\Config\Edit\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#38 Magento\Config\Block\System\Config\Edit\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#39 Magento\Config\Block\System\Config\Edit\Interceptor->___callPlugins() called at [generated/code/Magento/Config/Block/System/Config/Edit/Interceptor.php:32]
#40 Magento\Config\Block\System\Config\Edit\Interceptor->toHtml() called at [vendor/magento/framework/View/Layout.php:578]
#41 Magento\Framework\View\Layout->_renderBlock() called at [vendor/magento/framework/View/Layout.php:555]
#42 Magento\Framework\View\Layout->renderNonCachedElement() called at [vendor/magento/framework/View/Layout.php:510]
#43 Magento\Framework\View\Layout->renderElement() called at [vendor/magento/framework/View/Layout.php:606]
#44 Magento\Framework\View\Layout->_renderContainer() called at [vendor/magento/framework/View/Layout.php:557]
#45 Magento\Framework\View\Layout->renderNonCachedElement() called at [vendor/magento/framework/View/Layout.php:510]
#46 Magento\Framework\View\Layout->renderElement() called at [vendor/magento/framework/View/Layout.php:606]
#47 Magento\Framework\View\Layout->_renderContainer() called at [vendor/magento/framework/View/Layout.php:557]
#48 Magento\Framework\View\Layout->renderNonCachedElement() called at [vendor/magento/framework/View/Layout.php:510]
#49 Magento\Framework\View\Layout->renderElement() called at [vendor/magento/framework/View/Layout.php:606]
#50 Magento\Framework\View\Layout->_renderContainer() called at [vendor/magento/framework/View/Layout.php:557]
#51 Magento\Framework\View\Layout->renderNonCachedElement() called at [vendor/magento/framework/View/Layout.php:510]
#52 Magento\Framework\View\Layout->renderElement() called at [vendor/magento/framework/View/Layout.php:606]
#53 Magento\Framework\View\Layout->_renderContainer() called at [vendor/magento/framework/View/Layout.php:557]
#54 Magento\Framework\View\Layout->renderNonCachedElement() called at [vendor/magento/framework/View/Layout.php:510]
#55 Magento\Framework\View\Layout->renderElement() called at [vendor/magento/framework/View/Layout.php:606]
#56 Magento\Framework\View\Layout->_renderContainer() called at [vendor/magento/framework/View/Layout.php:557]
#57 Magento\Framework\View\Layout->renderNonCachedElement() called at [vendor/magento/framework/View/Layout.php:510]
#58 Magento\Framework\View\Layout->renderElement() called at [vendor/magento/framework/View/Layout.php:606]
#59 Magento\Framework\View\Layout->_renderContainer() called at [vendor/magento/framework/View/Layout.php:557]
#60 Magento\Framework\View\Layout->renderNonCachedElement() called at [vendor/magento/framework/View/Layout.php:510]
#61 Magento\Framework\View\Layout->renderElement() called at [vendor/magento/framework/View/Layout.php:606]
#62 Magento\Framework\View\Layout->_renderContainer() called at [vendor/magento/framework/View/Layout.php:557]
#63 Magento\Framework\View\Layout->renderNonCachedElement() called at [vendor/magento/framework/View/Layout.php:510]
#64 Magento\Framework\View\Layout->renderElement() called at [vendor/magento/framework/View/Layout.php:606]
#65 Magento\Framework\View\Layout->_renderContainer() called at [vendor/magento/framework/View/Layout.php:557]
#66 Magento\Framework\View\Layout->renderNonCachedElement() called at [vendor/magento/framework/View/Layout.php:510]
#67 Magento\Framework\View\Layout->renderElement() called at [vendor/magento/framework/View/Layout.php:975]
#68 Magento\Framework\View\Layout->getOutput() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:41]
#69 Magento\Framework\View\Layout\Interceptor->getOutput() called at [vendor/magento/framework/View/Result/Page.php:260]
#70 Magento\Framework\View\Result\Page->render() called at [vendor/magento/framework/View/Result/Layout.php:171]
#71 Magento\Framework\View\Result\Layout->renderResult() called at [generated/code/Magento/Backend/Model/View/Result/Page/Interceptor.php:32]
#72 Magento\Backend\Model\View\Result\Page\Interceptor->renderResult() called at [vendor/magento/framework/App/Http.php:120]
#73 Magento\Framework\App\Http->launch() called at [vendor/magento/framework/App/Bootstrap.php:264]
#74 Magento\Framework\App\Bootstrap->run() called at [pub/index.php:30]
</pre>

**Comment by roerlemans** [comment]
Thanks for your issue, we will fix this in our next release. I'll give you a notice after te new release. We apologize for the inconvenience.
