### ISSUE TITLE
Exception: Deprecated Functionality: explode()

### ISSUE THREAD

**Issue by Paulsky** [dhlparcel/plugin-magento2-release#51]
We are receiving an error when filtering orders in de backend:  

`main.CRITICAL: Exception: Deprecated Functionality: explode(): Passing null to parameter #2 ($string) of type string is deprecated in /vendor/dhlparcel/magento2-plugin/Ui/Column/Labels.php on line 95 in /vendor/magento/framework/App/ErrorHandler.php:62`

We are on: 
- Extension: 1.0.40
- Magento: 2.4.5
- PHP: 8.1

Please see: https://github.com/dhlparcel/plugin-magento2-release/issues/48#issuecomment-1480775501

**Comment by roerlemans** [comment]
Thanks for your issue, we will fix this in our next release. I'll give you a notice after te new release. We apologize for the inconvenience.

**Comment by Paulsky** [comment]
In which commit and file did you fix this?
