### ISSUE TITLE
Reason for exclusion of DE for servicePoints

### ISSUE THREAD

**Issue by tschallacka** [dhlparcel/plugin-magento2-release#52]
https://github.com/dhlparcel/plugin-magento2-release/releases/tag/v1.0.7

There is no reason said for the exclusion of the DE servicePoints

https://github.com/dhlparcel/plugin-magento2-release/blob/master/Model/Service/ServicePoint.php#L68

What is the reason for this?

**Comment by tschallacka** [comment]
@ronn0 @Dunduro

**Comment by roerlemans** [comment]
DE ServicePoints are showing. The reason PackStation's are hidden is because they need a consumer-specific number. Because the closest selection doesn't show any input-field this is skipped in the closest selection.

This if-statement does return DE Servicepoints which is no PackStation (a locker).
