### ISSUE TITLE
Exception: Deprecated Functionality: str_replace()

### ISSUE THREAD

**Issue by Paulsky** [dhlparcel/plugin-magento2-release#55]
We are receiving an error when viewing orders in de backend: 

`main.CRITICAL: Exception: Deprecated Functionality: str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in /vendor/dhlparcel/magento2-plugin/Model/Service/Preset.php on line 117 in /vendor/magento/framework/App/ErrorHandler.php:62`

We are on: 
- Extension: 1.0.40
- Magento: 2.4.5
- PHP: 8.1

**Comment by roerlemans** [comment]
We just released the new version which resolve this error. Our apologies for the inconvenience.

**Comment by Paulsky** [comment]
In which commit and file did you fix this?
