### ISSUE TITLE
Deprecated Functionality: trim(): Passing null to parameter #1 ($string)

### ISSUE THREAD

**Issue by Margero** [dhlparcel/plugin-magento2-release#57]
main.CRITICAL: Exception: Deprecated Functionality: trim(): Passing null to parameter #1 ($string) of type string is deprecated in /vendor/dhlparcel/magento2-plugin/Model/Api/Connector.php on line 176 in/vendor/magento/framework/App/ErrorHandler.php:62

Why is something so simple to fix taking so long?
I have been following this issue for over 4 weeks and still no release with the proper fix.

**Comment by roerlemans** [comment]
We just released the new version which resolve this error. Our apologies for the inconvenience.
