### ISSUE TITLE
Move Servicepoint options to shipping method block

### ISSUE THREAD

**Issue by FrankHarland** [dhlparcel/plugin-magento2-release#6]
Hi,

Other vendors such as PostNL / DPD display additional options for the selected shipping method in the same area as the shipping option.
DHL parcel does not which can make it harder for users to change the options of the shipping methods, especially when there is a large list of carriers.

For example; the difference between DPD and DHL
![image](https://user-images.githubusercontent.com/31548701/66819579-82538300-ef3f-11e9-8e4a-3c84dfad0ee9.png)

Wouldnt it be better to have the options for the DHL shipping method like this:
![image](https://user-images.githubusercontent.com/31548701/66819834-eaa26480-ef3f-11e9-95d9-7f7706bf98d7.png)

This seems a bit cleaner and more user-friendly.
Would it be possible to change this, or maybe add it as an option?

**Comment by petraheuts** [comment]
Hi Frank, thank you for adding this comment to our GitHub repository! We believe in developing according to the Magento standards. If we would add this custom ServicePoint component we would not be compatible with custom check-outs and face installation issues with our customers. Therefore our component is placed below the shipping methods following the Magento standards. In addition to the DPD extension we show the nearest DHL location alredy, so the user shouldn't have to switch it.

**Comment by roerlemans** [comment]
We did add the sort_order to the plugin. Thanks to Jeroen! For now we will close this issue.
