### ISSUE TITLE
php 8.2 compatability

### ISSUE THREAD

**Issue by davidtabat** [dhlparcel/plugin-magento2-release#60]
1 exception(s):
Exception #0 (Exception): Deprecated Functionality: Creation of dynamic property DHLParcel\Shipping\Model\Service\DeliveryTimes::$timeSelectionFactory is deprecated in /var/www/html/vendor/dhlparcel/magento2-plugin/Model/Service/DeliveryTimes.php on line 51

Exception #0 (Exception): Deprecated Functionality: Creation of dynamic property DHLParcel\Shipping\Model\Service\DeliveryTimes::$timeSelectionFactory is deprecated in /var/www/html/vendor/dhlparcel/magento2-plugin/Model/Service/DeliveryTimes.php on line 51
<pre>#1 DHLParcel\Shipping\Model\Service\DeliveryTimes->__construct() called at [vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:121]
#2 Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject() called at [vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:66]
#3 Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create() called at [vendor/magento/framework/ObjectManager/ObjectManager.php:70]
#4 Magento\Framework\ObjectManager\ObjectManager->get() called at [vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:170]
#5 Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument() called at [vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:276]
#6 Magento\Framework\ObjectManager\Factory\AbstractFactory->getResolvedArgument() called at [vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:239]
#7 Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgumentsInRuntime() called at [vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:34]
#8 Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments() called at [vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:59]
#9 Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create() called at [vendor/magento/framework/ObjectManager/ObjectManager.php:70]
#10 Magento\Framework\ObjectManager\ObjectManager->get() called at [vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:170]
#11 Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument() called at [vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:276]
#12 Magento\Framework\ObjectManager\Factory\AbstractFactory->getResolvedArgument() called at [vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:239]
#13 Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgumentsInRuntime() called at [vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:34]
#14 Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments() called at [vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:59]
#15 Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create() called at [vendor/magento/framework/ObjectManager/ObjectManager.php:70]
#16 Magento\Framework\ObjectManager\ObjectManager->get() called at [vendor/magento/framework/Interception/PluginList/PluginList.php:173]
#17 Magento\Framework\Interception\PluginList\PluginList->getPlugin() called at [vendor/magento/framework/Interception/Interceptor.php:144]
#18 Magento\Framework\View\Element\Template\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#19 Magento\Framework\View\Element\Template\Interceptor->___callPlugins() called at [generated/code/Magento/Framework/View/Element/Template/Interceptor.php:32]
#20 Magento\Framework\View\Element\Template\Interceptor->getTemplate() called at [vendor/magento/framework/View/Element/Template.php:290]
#21 Magento\Framework\View\Element\Template->_toHtml() called at [vendor/magento/framework/View/Element/AbstractBlock.php:1117]
#22 Magento\Framework\View\Element\AbstractBlock->Magento\Framework\View\Element\{closure}() called at [vendor/magento/framework/View/Element/AbstractBlock.php:1121]
#23 Magento\Framework\View\Element\AbstractBlock->_loadCache() called at [vendor/magento/framework/View/Element/AbstractBlock.php:670]
#24 Magento\Framework\View\Element\AbstractBlock->toHtml() called at [generated/code/Magento/Framework/View/Element/Template/Interceptor.php:302]
#25 Magento\Framework\View\Element\Template\Interceptor->toHtml() called at [vendor/magento/framework/View/Result/Page.php:251]
#26 Magento\Framework\View\Result\Page->render() called at [vendor/magento/framework/View/Result/Layout.php:171]
#27 Magento\Framework\View\Result\Layout->renderResult() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#28 Magento\Framework\View\Result\Page\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#29 Magento\Framework\View\Result\Page\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#30 Magento\Framework\View\Result\Page\Interceptor->___callPlugins() called at [generated/code/Magento/Framework/View/Result/Page/Interceptor.php:95]
#31 Magento\Framework\View\Result\Page\Interceptor->renderResult() called at [vendor/magento/framework/App/Http.php:120]
#32 Magento\Framework\App\Http->launch() called at [generated/code/Magento/Framework/App/Http/Interceptor.php:23]
#33 Magento\Framework\App\Http\Interceptor->launch() called at [vendor/magento/framework/App/Bootstrap.php:264]
#34 Magento\Framework\App\Bootstrap->run() called at [pub/index.php:30]
</pre>

**Comment by dennisvanderhammen-devnl** [comment]
Hi davidtabat,

Thank you for creating an issue on our repository.

I've created an item on our backlog to make our DHL plugin compatible with PHP8.1 and PHP8.2. I've added a link to this page to help us solve the issue faster.

**Comment by dennisvanderhammen-devnl** [comment]
Hi @davidtabat ,

We still have an issue open on our backlog to check other parts of our code for PHP8.2 compatibility, but the deprecation messages that you mentioned in your issue have just been resolved and pushed into a new version.

You can now download version v1.0.46.

**Comment by davidtabat** [comment]
Thank you
