### ISSUE TITLE
not working with  laminas-server 2.17.0

### ISSUE THREAD

**Issue by srgrbkl** [dhlparcel/plugin-magento2-release#63]
laminas removed laminas/laminas-zendframework-bridge and now module doesn't work https://github.com/laminas/laminas-server/releases

**Comment by dennisvanderhammen-devnl** [comment]
Hi @srgrbkl , do you think https://github.com/dhlparcel/plugin-magento2-release/pull/65 will fix your issues?
If not, could you please tell me what kind of problems you encounter?

**Comment by srgrbkl** [comment]
@dennisvanderhammen-devnl it works
