### ISSUE TITLE
Magento 2 issue 2.4.6-p4 php version 8.2

### ISSUE THREAD

**Issue by WebpleisterNL** [dhlparcel/plugin-magento2-release#66]
I get the next issue when I trying to install the package in composer :

There is an error in /home/u178518p234966/domains/alchemistshop.nl/public_html/vendor/dhlparcel/magento2-plugin/Ui/Bulk/Actions.php at line: 8
Interface "Zend\Stdlib\JsonSerializable" not found#0 /home/u178518p234966/domains/alchemistshop.nl/public_html/vendor/composer/ClassLoader.php(576): include()
#1 /home/u178518p234966/domains/alchemistshop.nl/public_html/vendor/composer/ClassLoader.php(427): Composer\Autoload\{closure}()
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass()
#3 /home/u178518p234966/domains/alchemistshop.nl/public_html/vendor/magento/framework/ObjectManager/Relations/Runtime.php(38): class_exists()
#4 /home/u178518p234966/domains/alchemistshop.nl/public_html/vendor/magento/framework/Interception/Config/Config.php(157): Magento\Framework\ObjectManager\Relations\Runtime->has()
#5 /home/u178518p234966/domains/alchemistshop.nl/public_html/vendor/magento/framework/Interception/Config/Config.php(151): Magento\Framework\Interception\Config\Config->_inheritInterception()
#6 /home/u178518p234966/domains/alchemistshop.nl/public_html/vendor/magento/framework/Interception/Config/Config.php(180): Magento\Framework\Interception\Config\Config->_inheritInterception()
#7 /home/u178518p234966/domains/alchemistshop.nl/public_html/vendor/magento/framework/Interception/Config/Config.php(213): Magento\Framework\Interception\Config\Config->hasPlugins()
#8 /home/u178518p234966/domains/alchemistshop.nl/public_html/vendor/magento/framework/Interception/Config/Config.php(190): Magento\Framework\Interception\Config\Config->generateIntercepted()
#9 /home/u178518p234966/domains/alchemistshop.nl/public_html/vendor/magento/framework/Interception/Config/Config.php(122): Magento\Framework\Interception\Config\Config->initializeUncompiled()
#10 /home/u178518p234966/domains/alchemistshop.nl/public_html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(121): Magento\Framework\Interception\Config\Config->__construct()
#11 /home/u178518p234966/domains/alchemistshop.nl/public_html/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(66): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject()
#12 /home/u178518p234966/domains/alchemistshop.nl/public_html/vendor/magento/framework/ObjectManager/ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create()
#13 /home/u178518p234966/domains/alchemistshop.nl/public_html/vendor/magento/framework/App/ObjectManager/Environment/Developer.php(84): Magento\Framework\ObjectManager\ObjectManager->get()
#14 /home/u178518p234966/domains/alchemistshop.nl/public_html/vendor/magento/framework/App/ObjectManagerFactory.php(191): Magento\Framework\App\ObjectManager\Environment\Developer->configureObjectManager()
#15 /home/u178518p234966/domains/alchemistshop.nl/public_html/vendor/magento/framework/App/Bootstrap.php(212): Magento\Framework\App\ObjectManagerFactory->create()
#16 /home/u178518p234966/domains/alchemistshop.nl/public_html/vendor/magento/framework/App/Bootstrap.php(127): Magento\Framework\App\Bootstrap->__construct()
#17 /home/u178518p234966/domains/alchemistshop.nl/public_html/vendor/magento/framework/Console/Cli.php(185): Magento\Framework\App\Bootstrap::create()
#18 /home/u178518p234966/domains/alchemistshop.nl/public_html/vendor/magento/framework/Console/Cli.php(85): Magento\Framework\Console\Cli->initObjectManager()
#19 /home/u178518p234966/domains/alchemistshop.nl/public_html/bin/magento(22): Magento\Framework\Console\Cli->__construct()
#20 {main}

**Comment by dennisvanderhammen-devnl** [comment]
Hi @WebpleisterNL,

Thank you for telling us about this issue. We have just now released version v1.0.46 of our plugin which contains a fix for this issue. See https://github.com/dhlparcel/plugin-magento2-release/pull/65.
