### ISSUE TITLE
Not possible to create labels in sales grid in Magento 2.3.3

### ISSUE THREAD

**Issue by mikehenze** [dhlparcel/plugin-magento2-release#8]
The DHL plugin does not seem to work with the latest Magento (2.3.3).
The sales grid is not loading but this fixed it:
https://github.com/dhlparcel/plugin-magento2-release/pull/5

But after the fix we are also not able to create labels using the action menu in sales grid.
Select order > Actions >  DHL Parcel > Create Label
Result: Error 404 (no error logged)
https://www.domain.com/admin/create/index/index/key/aeecb59c1ahghjc8e5f0a7e16b8b53f5415379d4fb878a588008ce1ced8ea2eb758f/

**Comment by Nielex** [comment]
I think this is a new issue and has something todo with the "setasign/fpdi-fpdf" library from version 1.0.6.

For me its also not possible to print any labels, on my development env. where PHP errors is turned on I got the following error with stacktrace. 

![Screenshot 2019-11-05 at 12 56 29](https://user-images.githubusercontent.com/5550238/68206047-10191000-ffcc-11e9-8722-2280e372822f.png)

I think the implementation of this library is not totally done right. My work around is to roll back to version 1.0.5 of this module.

**Comment by jwbos-uhg** [comment]
We have the same problem on Magento 2.2.10. We needed the fix the first problem:
The sales grid is not loading but this fixed it: #5

Now we also have the 404 page not found error.

**Comment by petraheuts** [comment]
Hi all,
We fixed the compatibility with the new Magento version 2.3.3. in release 1.0.8. So this should work now.
Best regards,
Petra

**Comment by FedeltaMedia** [comment]
We have the same problem on 1.0.12 on Magento 2.3.4:
`Fatal error: Class 'FPDF' not found in /application/vendor/setasign/fpdi/src/FpdfTpl.php on line 19`

**Comment by petraheuts** [comment]
Thnx Maurice for informing us, we will check this.

**Comment by petraheuts** [comment]
> We have the same problem on 1.0.12 on Magento 2.3.4:
> `Fatal error: Class 'FPDF' not found in /application/vendor/setasign/fpdi/src/FpdfTpl.php on line 19`

Hi Maurice, hoe heb je de DHL plug-in geïnstalleerd?

**Comment by FedeltaMedia** [comment]
@petraheuts Hi Petra! Sorry, zie je reactie nu pas. De installatie is via de losse release gedaan (dus niet via composer).
Zie wel dat er inmiddels een versie 1.0.13 uit is waar ik getest had met versie 1.0.12. Zal deze morgen updaten om te zien of het probleem is opgelost!

**English:**
I'll try version 1.0.13 tomorrow and will update back here if that fixed the problem.

**Comment by FedeltaMedia** [comment]
Updating to 1.0.13 did not fix this issue

Edit:
Problem was fixed by adding setasign/fpdi-fpdf:
`composer require setasign/fpdi-fpdf`
