### ISSUE TITLE
Selecting DHL Pickup Point location is not reflected in the shipping address

### ISSUE THREAD

**Issue by PTuijtelaars-ISAAC** [dhlparcel/plugin-magento2-release#9]
When a customer has selected a DHL Pickup point during checkout the customer receives an email with the wrong shipping address. The address mentioned in the email is the shipping address of the customer and not the address of the DHL Pickup point. 

During checkout there is also an option to use the same address for invoice and shipping. This is strange. The order is shipped to a pickup point and not to the invoice address. 

We currently use Magento 2.2.10 with DHL Parcel 1.0.8 installed.

**Comment by petraheuts** [comment]
We've fixed this issue, thank you for contributing!
